### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by elico** [looterz/grimd#62]
I have just compiled Latest commit 50dc846 from 3 days ago.
When I tested it I a got the next result:
```
# dig @127.0.0.1 google.com
panic: send on closed channel

goroutine 28 [running]:
main.(*DNSHandler).DoUDP(...)
        /home/eliezer/Scripts/grimd/handler.go:275
main.(*DNSHandler).DoUDP-fm(0xca4740, 0xc0003d8000, 0xc00021e510)
        /home/eliezer/Scripts/grimd/server.go:29 +0x80
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00031c630, 0xca4740, 0xc0003d8000, 0xc00021e510)
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/server.go:52 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc000318880, 0xca4740, 0xc0003d8000, 0xc00021e510)
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/serve_mux.go:128 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc0001b0a00, 0xc0003d8000)
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/server.go:687 +0x2c1
github.com/miekg/dns.(*Server).serve(0xc0001b0a00, 0xc0003d8000)
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/server.go:572 +0x2a7
github.com/miekg/dns.(*Server).worker(0xc0001b0a00, 0xc0003d8000)
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/server.go:244 +0x4d
created by github.com/miekg/dns.(*Server).spawnWorker
        /home/eliezer/go/pkg/mod/github.com/miekg/dns@v1.1.4/server.go:284 +0x86
```

I can test if it's a regression but, am I the first to see such an issue?
grimd.conf
```
# version this config was generated from
version = "1.0.6"

# list of sources to pull blocklists from, stores them in ./sources
sources = [
]

# list of locations to recursively read blocklists from (warning, every file found is assumed to be a hosts-file or domain list)
sourcedirs = [
"sources"
]

# log configuration
# format: comma separated list of options, where options is one of
#   file:<filename>@<loglevel>
#   stderr>@<loglevel>
#   syslog@<loglevel>
# loglevel: 0 = errors and important operations, 1 = dns queries, 2 = debug
# e.g. logconfig = "file:grimd.log@2,syslog@1,stderr@2"
logconfig = "file:grimd.log@2,stderr@2"

# apidebug enables the debug mode of the http api library
apidebug = false

# address to bind to for the DNS server
bind = "0.0.0.0:53"

# address to bind to for the API server
api = "127.0.0.1:8080"

# ipv4 address to forward blocked queries to
nullroute = "0.0.0.0"

# ipv6 address to forward blocked queries to
nullroutev6 = "0:0:0:0:0:0:0:0"

# nameservers to forward queries to
nameservers = ["1.1.1.1:53", "8.8.8.8:53"]

# concurrency interval for lookups in miliseconds
interval = 200

# query timeout for dns lookups in seconds
timeout = 5

# cache entry lifespan in seconds
expire = 600

# cache capacity, 0 for infinite
maxcount = 0

# question cache capacity, 0 for infinite but not recommended (this is used for storing logs)
questioncachecap = 5000

# manual blocklist entries
blocklist = []

# Drbl related settings
usedrbl = 0
drblpeersfilename = "drblpeers.yaml"
drblblockweight = 128
drbltimeout = 30
drbldebug = 1

# manual whitelist entries
whitelist = [
        "getsentry.com",
        "www.getsentry.com"
]

# When this string is queried, toggle grimd on and off
togglename = ""

# If not zero, the delay in seconds before grimd automaticall reactivates after
# having been turned off.
reactivationdelay = 300

#Dns over HTTPS provider to use.
DoH = "https://cloudflare-dns.com/dns-query"

```

**Comment by ryancdotorg** [comment]
Should this be closed?

**Comment by elico** [comment]
@ryancdotorg I will try to test it later.

**Comment by elico** [comment]
@ryancdotorg Seems to be resolved on master.
@looterz is it time for 1.7?
